# infra/docker-compose.yml
version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cropsense_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mlflow:
    image: mlfloworg/mlflow:latest
    container_name: cropsense_mlflow
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0
    volumes:
      - ./mlflow:/mlflow
